version: '{build}'
clone_depth: 1

image:
  # - Visual Studio 2019
  - Ubuntu

environment:
  DOCKER_PASSWORD:
     secure: 5thIPcBWPN+Qcha5VkR8Ng== 

branches:
  only:
    - master
    - dev

configuration:
  - Release

init:
  - git config --global core.autocrlf true

before_build:
  - ps: dotnet --info
  - ps: "Get-ChildItem Env:"

build_script:
 - ps: sudo docker build -t apollo3zehn/minimail:1.0.0.alpha.1.$Env:APPVEYOR_BUILD_NUMBER .

after_test:
  - ps: docker login -u="apollo3zehn" -p="$env:DOCKER_PASSWORD"
  - ps: docker push apollo3zehn/minimail:1.0.0.alpha.1.$Env:APPVEYOR_BUILD_NUMBER